server:
  address: ":8080"
  read_timeout: "5s"
  write_timeout: "10s"
  idle_timeout: "15s"
  shutdown_timeout: "30s"
  request_timeout: "45s"

db:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  dbname: "example"
  sslmode: "disable"
  migrations: "./migrations"

storage:
  bucket: example
  access_key_id: admin
  secret_key_id: password
  endpoint: "localhost:9000"